# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.



[[main]]
  name = "Visualization Tools"
  url = "#dashboards"
  weight = 09

[[main]]
  name = "About"
  url = "#about01"
  weight = 11

[[main]]
  name = "Resources"
  url = "#technical_resources"
  weight = 10

[[main]]
  name = "Partners"
  url = "research-team/"
  weight = 25

[[main]]
  name = "Partners"
  url = "partners/"
  weight = 25

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 30

[[main]]
  name = "CCDD"
  url = "https://ccdd.hsph.harvard.edu/covid-19-research/"
  weight = 35

[[main]]
  name = "Member Login"
  url = "https://3.basecamp.com/4418925/projects"
  weight = 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
